[package]
name = "domaintwistex"
version = "0.1.0"
edition = "2021"

[lib]
name = "domaintwistex"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.1"
twistrs = "0.7.0"
futures = "0.3"
